# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/136CVEhnNR_uT4Av-Qt6qyaoxNphnFreX
"""

!pip list

"""## imports"""

import numpy as np
import tensorflow as tf
from keras.preprocessing.image import img_to_array, load_img
from keras.applications.inception_resnet_v2 import InceptionResNetV2, decode_predictions, preprocess_input

from IPython.core.display import display

"""##Constants"""

FILE_1 = '01 Umbrella.jpg'
FILE_2 = '02 Couple.jpg'
FILE_3 = '03 Ocean.jpg'

"""## preprocessing images"""

pic = load_img(FILE_1, target_size=(299, 299))
display(pic)

pic_array = img_to_array(pic)
pic_array.shape

expanded = np.expand_dims(pic_array, axis=0)
expanded.shape

preprocessed = preprocess_input(expanded)

"""## Load InceptionResNet"""

# Commented out IPython magic to ensure Python compatibility.
# %%time
# 
# inception_model = InceptionResNetV2(weights= 'imagenet')

inception_model.graph = tf.get_default_graph()

"""## making predictions"""

# inception_model.predict(pic_array) 
prediction = inception_model.predict(preprocessed)

decode_predictions(prediction)

